routes/web.php
<?php

Route::resource('profile', 'UserController')->middleware('auth');
Route::post('register/user', 'UserController@store');
Route::get('register', 'UserController@register');
// Route::get('/profile','UserController@index')->middleware('auth');

Route::get('/', 'AuthenticationController@login')->name('loginPage');
Route::post('login', 'AuthenticationController@authenticate');
Route::get('/logout', 'AuthenticationController@logout');

Route::resource('contacts', 'ContactController')->middleware('auth');
Route::get('/excel', 'ContactController@excelIndex')->middleware('auth')->name('contacts.excel');
Route::get('/contacts/favorite/{id}', 'ContactController@favorite')->name('contacts.favorite');
Route::get('/search', 'ContactController@search')->middleware('auth');
Route::put('block/{id}', 'ContactController@block')->name('block');
Route::put('unblock/{id}', 'ContactController@unblock')->name('unblock');

Route::post('/verificanew', 'VerifyEmailController@sendNewVerifyEmail');
Route::get('login/token/{token}', 'VerifyEmailController@verifyEmail');
Route::get('/verify/email', 'VerifyEmailController@index');

Route::resource('suporte', 'SuporteController')->middleware('auth');

Route::get('/excel/search', 'ExportExcelController@search')->middleware('auth');
Route::post('/export_excel/excel', 'ExportExcelController@excel')->name('export_excel.excel');
Route::get('/export_excel', 'ExportExcelController@index')->middleware('auth');

Route::resource('categories', 'CategoryController')->middleware('auth');

Route::get('dashboard', 'EventController@index')->middleware('auth');
Route::post('dashboard.store', 'EventController@store')->middleware('auth')->name("dashboard.store");
Route::get('/dashboard/events', 'EventController@eventsView')->middleware('auth')->name("dashboard.events");
Route::patch('/dashboard/events/{id}', 'EventController@update')->middleware('auth')->name("dashboard.update");
Route::DELETE('/dashboard/events/{id}', 'EventController@destroy')->middleware('auth')->name("dashboard.destroy");

Route::DELETE('/phone/delete/{id}', 'PhoneController@destroy')->middleware('auth')->name("phone.destroy");

Route::get('contact/import/google', ['as' => 'google.import', 'uses' => 'GoogleContactController@importGoogleContact'])
->middleware('auth');

Route::resource('addGoogleContacts', 'GoogleContactController')->middleware('auth');

resources/views/addGoogleContact.blade.php
@extends('navbar')
@section('content')
<head>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/patternfly/3.24.0/css/patternfly-additions.min.css">
</head>
<body class="cards-pf">
    {!! Form::open(['route' => 'addGoogleContacts.store', 'id'=>'myForm']) !!}
    {{ csrf_field() }}
        @if (count($errors) > 0 )
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>    
                    @endforeach
                </ul>
            </div>
        @endif
        @csrf
        <div class="col-md-12">
            <div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">
                <h1>Escolha o(s) contato(s)</h1>
                <p style="display:none" id="todos_up">Escolher todos <input type="checkbox" class="check" id="checkAll">  
            </div>

            <div class="addbutton col-xs-12 col-sm-4 col-md-6 col-lg-6">
                <button type="submit" id="add" class="botao_import btn btn-info">Importar contatos selecionados</button>
                <p style="display:none" id="todos_down">Escolher todos <input type="checkbox" class="check" id="checkAll_down">  

            </div>
        </div>
        <div class="container-fluid container-cards-pf" id="card-container">
            <div   class="row row-cards-pf">
                @forelse ($contact as $contact)
                    <div class="col-xs-12 col-sm-4 col-md-3 col-lg-2">
                        <div class="card-pf card-pf-view card-pf-view-select card-pf-view-multi-select">
                            <div  class="card-pf-body">
                                
                                <p class="card-pf-info text-center">
                                    <input  type="checkbox" id="checkb" name="contact[]" onchange="enable(this)"  class="pull-left check">
                                    <strong>Nome:</strong> 
                                </p>

                                <p><textarea maxlength="35" name="name[]" id="inp" cols="20" disabled class="name" rows="2">{{$contact['name'] }}</textarea>
                                </p>
                                <p  class="card-pf-info text-center"><strong>Email:</strong>
                                    <p><textarea name="email[]" maxlength="35" id="inp" cols="20" disabled class="email" rows="2">{{$contact['email'] }}</textarea>
                                    </p>
                                <p class="card-pf-info text-center"><strong>Telefone:</strong>
                                    <input  id="inp" class="phone" type="text" required name="phone[]" disabled  value="{{$contact['phone'] }}">
                                </p>
                            </div>
                        </div>
                    </div>
                @empty
                    <p>Sua conta não tem nenhum contato :/</p>    

                @endforelse
            </div>
        </div>
        <a id="back2Top" title="Back to top" href="#">&#10148;</a>

    {!! Form::close() !!}

<script type="text/javascript" src="/js/addgooglecontact.js"></script>
<link rel="stylesheet" type="text/css"  href="{!!  asset('/css/addGoogleContact.css') !!}" type="text/css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/patternfly/3.24.0/js/patternfly.min.js"></script>


<script>
function funcaowid(x) {
  if (x.matches) { // If media query matches
    document.getElementById("todos_up").style.display="none"
    document.getElementById("todos_down").style.display="block"

  } else {
    document.getElementById("todos_down").style.display="none";
    document.getElementById("todos_up").style.display="block"


  }
}

var x = window.matchMedia("(max-width: 768px)")
console.log(x);
funcaowid(x) // Call listener function at run time
x.addListener(funcaowid) // Attach listener function on state changes
</script>

@stop

resources/views/block.blade.php
@extends('navbar')
@section('content')
<div class="container">

    <div class="row">

      {{-- <div class="container col-lg-4">
        <p>telefones</p>
          <ul class="list-group">
            @forelse ($phones as $phone)

              <li class="list-group-item">{{ $phone->phone}} {{ $phone->contact_id  }} </li>

              @empty
                  <p>nenhum contato registrado :)</p>
            @endforelse

          </ul>
        </div> --}}
      <div class="table-responsive">
          @if (count($errors) > 0 )
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
      @endif
      @if($blockedContacts->count() > 0)
        <table class="table table-striped " >
          <thead>
              <tr>
              <th class="text-center">Nome</th>
              <th class="text-center">Email</th>
              <th></th>
              <th></th>
              </tr>
          </thead>
          <tbody>
            @foreach ($blockedContacts as $contact)
              <tr>
                <td class="text-center" style="vertical-align: middle;">{{$contact->name }}</td>
                <td class="text-center" style="vertical-align: middle;">{{$contact->email }}</td>
                <td>
                  <div class="row">
                    <div class="col-md-2">
                      <a style="text-decoration: none;" href="/contacts/{{ $contact->id }}/edit">
                        <button class="btn btn-warning" type="button">
                          edit
                        </button>
                      </a>
                    </div>
                    <div class="col-md-2">
                      <form action="/unblock/{{ $contact->id }}" method="POST">
                        @method('PUT')
                        @csrf
                        <button  name="unblockUserId" value="{{ $contact->id }}"  type="btn-submit" class="btn btn-default">
                          unblock
                        </button>
                      </form>
                    </div>
                  </div>
                </td>
                <td>
                  {!!Form::open(['action' => ['ContactController@destroy', $contact->id], 'method' => 'POST', 'class' => 'pull-right'])!!}
                    {{Form::hidden('_method', 'DELETE')}}
                    {{Form::submit('Delete', ['class' => 'btn btn-danger' ,'onclick'=>"return confirm('Tem certeza que deseja deletar esse contato?')"])}}
                  {!!Form::close()!!}
                </td>
              </tr>
            @endforeach
          </tbody>
        </table>
      @else
        <p>nenhum contato bloqueado :)</p>
      @endif
      </div>
    </div>


@stop

resources/views/contacts.blade.php
@extends('navbar')
<body onchange="funcaowid()">

@section('content')
  <div class="container">
    <div class="row">
      @if (count($errors) > 0 )
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
      @endif
      <div class="text-center">
          <h1>Meus Contatos</h1>
      </div>
    </div>
    <div class="row">
      @if($contacts->count() > 9)
        <div class="col-md-3 col-sm-12 pull-right">
          <form action="/search" method="GET">
            <label for="search">Procure um contato:</label>
            <div class="input-group">
              <input type="search" placeholder="nome do contato:" name="search" class="form-control">
              <span class="input-group-btn">
                  <button type="submit" class="btn btn-primary" >
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                  </button>
              </span>
            </div>
          </form>
        </div>
      @endif

      <a style="margin-top:2%;" href="{{ route('contacts.excel') }}" class="btn btn-success ">Exportar em Excel</a>

      <button style="margin-top:2%;" class="btn btn-info" onclick="myFunction()">Importar contatos da google</button>
    </div>

    <div class="row">
      <div class="table-responsive">
        <table class="table table-striped " >
          @if($contacts->count() > 0)
            <thead>
              <tr>
                <th class="text-center">Nome</th>
                <th class="text-center">Email</th>
              </tr>
            </thead>
          @endif
          <tbody>
            @forelse ($contacts as $contact)
              <tr class="text-center">
                <td style="vertical-align: middle;">{{$contact->name }}</td>
                <td style="vertical-align: middle;">{{$contact->email }}</td>
                <td>
                  <label style="vertical-align: middle;">
                    <a style="text-decoration: none;" href="/contacts/{{ $contact->id }}/edit">
                      <button class="btn btn-warning" type="button">
                        editar
                      </button>
                    </a>
                  </label>

                  <label style="vertical-align: middle;">
                    <form action="/block/{{ $contact->id }}" method="POST">
                      @method('PUT')
                      @csrf
                      <button name="blockUserId" value="{{ $contact->id }}" type="btn-submit" class="btn"
                        onclick='return confirm("Tem certeza que deseja bloquear esse contato? ")' >
                        bloquear
                      </button>
                    </form>
                  </label>

                  <label disabled style="vertical-align: middle;">
                      {!!Form::open(['action' => ['ContactController@destroy', $contact->id], 'method' => 'POST', 'class' => 'pull-right'])!!}
                        {{Form::hidden('_method', 'DELETE')}}
                        {{  Form::submit('Deletar', ['class' => 'btn btn-danger','onclick'=>"return confirm('Tem certeza que deseja deletar esse contato?')"])}}
                      {!!  Form::close()!!}
                  </label>

                  @if($contact->favorite==1)
                    <form action="/contacts/favorite/{{ $contact->id }}" style="margin-right:8%;" class="pull-right" method="GET">
                      <label class="container2">
                        <input style="display:none" onchange="this.form.submit()" type="checkbox" name="{{ $contact->name }}" value="{{$contact->id}}">
                        <span checked type="checkbox" value="aoaoao" id="{{ $contact->id }}" class="star glyphicon glyphicon-star"></span>
                      </label>
                    </form>
                  @endif

                  @if($contact->favorite==0)
                        <form action="/contacts/favorite/{{ $contact->id }}" style="margin-right:8%;" class="pull-right" method="GET">
                          <label class="container2">
                            <input style="display:none" onchange="this.form.submit()" type="checkbox" name="{{ $contact->name }}" value="{{$contact->id}}">
                            <span type="checkbox" value="aoaoao" id="{{ $contact->id }}" class="star glyphicon glyphicon-star-empty"></span>
                          </label>
                        </form>
                    </td>
                  @endif
                </td>
              </tr>
            @empty
                <p>nenhum contato registrado :)</p>
            @endforelse
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="container-fluid" id="linha">
          <span class="pull-left" id="pagi">{{ $contacts->links() }}</span>

          <a class="col-md-6" id="cria_contact" class=" nav-link" href="contacts/create">
            <button class="btn btn-primary" id="cria_contato_up_row" type="button">criar novo contato</button>
          </a>
      </div>
    </div>
    <div class="row">
      <a id="cria_contact" class=" nav-link" href="contacts/create">
        <button class="btn btn-primary" id="cria_contato_down_row" type="button">criar novo contato</button>
      </a>
      <a class="nav-link" style=" color: white; border" href="contacts/block">
        <button  style="background-color:grey;" id="block_contact" class="btn pull-right" type="button">contatos bloqueados</button>
      </a>
    </div>
  </div>
</body>
  <script src="/js/contacts.js"></script>
  <link rel="stylesheet" type="text/css"  href="{!!  asset('/css/contacts.css') !!}" type="text/css">
@stop

resources/views/contactsExcel.blade.php
@extends('navbar')
@section('content')
    <div class="container">

        <div class="row">
            @if (count($errors) > 0 )
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </div>
        <div class="text-center">
            <h1>Excel Contacts</h1>
        </div>

        <div class="row">
            <div class="col-sm-12">
                 @if($contacts->count() > 9)
                    <div class="col-lg-3  pull-right">
                        <form action="/excel/search" method="GET">
                        <p>Procure um contato:</p>
                        <div class="input-group">
                            <input type="search" placeholder="nome do contato:" name="search" class="form-control">
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-primary" >
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                </button>
                            </span>
                        </div>
                        </form>
                    </div>
                @endif

                <button type="button" style="margin-top:3%;" class="btn btn-info" onclick="myFunction()">Importar contatos da google</button>
                {!! Form::open(['route' => 'export_excel.excel', 'id'=>'myForm']) !!}
                {{ csrf_field() }}
            </div>
        </div>
        <div class="row">
            <div class="table-responsive">
                <table class="table table-striped " >
                    @if($contacts->count() > 0)
                        <thead>
                            <tr>
                                <th class="text-center">Nome</th>
                                <th class="text-center">Email</th>
                                <th style="text-align:center;"><input type="checkbox" style="vertical-align: middle; " onclick="toggle_inputs(this)" class="check" id="checkAll"></th>
                            </tr>
                        </thead>
                    @endif
                    <tbody>
                        @forelse ($contacts as $contact)
                            <tr class="text-center">

                                <input name="contactid[]"  disabled class="contact_id" id="contact-id" value="{{$contact->id}}" type="hidden">
                                <td style="vertical-align: middle;"><input id="inp" type="text" class="name" name="name[]" disabled  value="{{$contact->name }}"></td>
                                <td style="vertical-align: middle;"><input id="inp" class="email" type="text" name="email[]" disabled  value="{{$contact->email }}"></td>
                                <td><input type="checkbox" id="checkb" name="contact[]" onchange="enable(this)"  class="check"></td>

                            </tr>
                        @empty
                            <p>nenhum contato registrado :)</p>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <span id="pagi" class="line">{{ $contacts->links() }}</span>

            <a href="{{ route('export_excel.excel') }}">
                <button type="submit" class="line btn btn-success pull-right">Exportar</button>
            </a>
    </div>
    {!! Form::close() !!}
    <script src="/js/contactexcel.js"></script>

    <style>

        .line{
            display: inline-block;

        }
        .pagination{
            margin:0;
        }

        input[type=text] {
            border: none;
            background-color: transparent;
        }
    </style>

@stop

resources/views/navbar.blade.php
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        {{-- <link rel="shortcut icon" href="{{ asset('https://img.icons8.com/cotton/64/000000/calendar.png') }}"> --}}
        <title>Agenda</title>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.js"></script>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

        <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/js/bootstrap-multiselect.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/css/bootstrap-multiselect.css">

        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <style>
            .gildo{
                margin-top:15px;
            }
            p{
                margin-top:5px;
            }

            #logout_button , #perfil_button {
            display:inline-block;
            /**other codes**/
            }
            .navbar{
                border-radius: 0;
            }

            .container{
                background-color: rgba(0,0,0,0.1);
                padding:20px;
                border:2px solid;
                border-color:rgba(0,0,0,0.25 );
            }

            .button-margin{
                margin-top:20px;
            }

            .center-block {
                display: block;
                margin-left: auto;
                margin-right: auto;
            }
            #endere{
                text-align: center;
            }

            form{
                margin:0;
            }

        </style>
    </head>
    <body>
        <nav class="navbar navbar-inverse" style="margin-bottom:0px">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/dashboard">Eventos</a>
                </div>

                <div class="collapse navbar-collapse"  id="bs-example-navbar-collapse-1">

                    <ul class="nav navbar-nav" >
                    <li><a href="/contacts">Contatos</a></li>
                    <li><a href="/categories">Categoria</a></li>
                    <li><a href="/suporte">Suporte</a></li>
                    </ul>

                    {{-- <form method="POST" class="pull-right" action='/logout'>
                        @csrf --}}

                    <a href="/logout"> <button style="margin-top:0.6%; margin-left:0.5%; " id="logout_button" class="pull-right btn btn-sm btn-danger"
                        style="vertical-align: middle;"  type="button" >
                            Sair
                        </button></a>
                    {{-- </form> --}}

                    <button style="vertical-align: middle; margin-top:0.6%;" id="perfil_button"    type="button" class="pull-right btn btn-sm btn-info" data-toggle="modal" data-target="#exampleModal">
                            Perfil
                        </button>
                    <h4 class="pull-right" style="vertical-align: middle; margin-right:10px; margin-top:1%; color:white">
                        Logado como( {{ Auth::user()->user_name }} )
                    </h4>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <div class="pull-right col-md-2">
            @include('flash::message')
        </div>
        @yield('content')
    </body>
</html>


<script>
    function copia_api_token() {
        /* Get the text field */
        console.log("foi");
        var copyText = document.getElementById("api_token");

        /* Select the text field */
        copyText.select();
        /* Copy the text inside the text field */
        document.execCommand("copy");

        /* Alert the copied text */
        alert("Texto copiado: " + copyText.value);
        }
</script>
<!-- Modal -->
<div class="modal fade"  id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content" style="width:86%; margin-left:14%;">
            <div class="modal-header">
            <h2 class="modal-title" id="exampleModalLabel">Perfil</h2>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body" >
            <form action="{{ route('profile.update','test' )}}" method="POST">
            {{ method_field('patch')}}
            {{ csrf_field() }}
            <p>Nome:
                <div class="input-group">
                    <input id="name" name="user_name" type="text" class="form-control" disabled value="{{ auth()->user()->user_name }}">
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-warning" onclick="edit_name()">editar</button>
                    </span>
                </div><!-- /input-group -->
            </p>
            <p>Email:
                <div class="input-group">
                    <input id="userEmail" type="email" name="email" class="form-control" disabled value="{{ auth()->user()->email }}">

                    <span class="input-group-btn">
                    <button type="button" onclick="edit_email()" class="btn btn-warning">editar</button>

                    </span>
                </div><!-- /input-group -->
            </p>
            <input type="text" hidden name="id" value="{{ auth()->user()->id }}">
            <p>
                <button class="btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    API-Key
                </button>
            </p>

            <div class="collapse" id="collapseExample">

                <input  id="api_token" class="form-control" type="text" value="{{ auth()->user()->api_token }}">

                <button type="button" onclick="copia_api_token()" class="btn btn-info">
                    <span class="glyphicon glyphicon-copy" aria-hidden="true">copiar</span>
                </button>
            </div>

            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Sair</button>

                <button type="submit" class="btn btn-primary">Salvar</button>
            </form>
            </div>
        </div>
    </div>
    <script>
        $('div.alert').not('.alert-important').delay(2000).fadeOut(450);
    </script>
</div>

<script type="text/javascript" src="/js/navbar.js"></script>

resources/views/newcategory.blade.php
@extends('navbar')
@section('content')

    <div class="container">

        <h1 style="text-align: center">Criação de categoria</h1>

        {!! Form::open(['route' => 'categories.store']) !!}
        
            <div class="form-row" >

                <div class="col-md-12 text-center button-margin">
                    <div class="col-md-6">
                        <label for="category"><h2>Nova categoria</h2></label>
                        <input type="text" name="category" class="form-control" id="category" placeholder="categoria" required>
                        <button class="btn btn-primary" type="submit" style="margin-top:5%;">Criar categoria</button>
                    </div>
        {!!Form::close()!!}
                    <div class="col-md-6">
                        <label for="category"><h2>Suas Categorias</h2></label>

                        <table class="table table-striped" >
                            <tbody>
                                @forelse($category as $id=>$categorie)
                                        <tr class="text-center">
                                            <td style="vertical-align: middle;">{{$categorie }}</td>
                                            <td>
                                                <button type="button" class="edit_button btn btn-warning" 
                                                data-category_id="{{ $id }}" data-mycategory="{{ $categorie }}" 
                                                data-toggle="modal" data-target=".edit">
                                                    editar
                                                </button>

                                                {!!Form::open(['action' => ['CategoryController@destroy', $id],
                                                'method' => 'POST', 'class' => 'pull-right'])!!}

                                                {{Form::hidden('_method', 'DELETE')}}
                                                {{Form::submit('Deletar', ['class' => 'btn btn-danger'])}}
                                                {!!Form::close()!!}
                                            </td>
                                        </tr>
                                        @empty
                                        <p>você não tem categorias</p>

                                                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> <p> crie uma ao lado :)</p>
                                @endforelse
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>

            <div class="edit modal" tabindex="-1" role="dialog">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h3 class="modal-title">Edite sua Categoria abaixo</h3>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <form action="{{ route('categories.update','test' )}}" method="POST">
                            {{ method_field('patch')}}
                            {{ csrf_field() }}
                            <div class="modal-body">
                                <input type="text" id="categoryy" name="category" placeholder="categoria" class="categoria form-control" 
                                required="required"/>
                                <input type="hidden" id="cat_id" name="category_id"  class=" form-control"/>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Sair</button>
                                <button type="submit" class="btn btn-primary" >Salvar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
<script type="text/javascript" src="/js/newcategory.js"></script>
                
<style>
@media only screen and (min-width: 284px) and (max-width:348px) {
    .edit_button{
        margin-left: 35%;
    }
}
</style>
@stop

resources/views/profile.blade.php
@extends('navbar')
@section('content')

<body>
    <div class="container">
        <h2>Minha Conta</h2>
        {{-- @foreach --}}
        <p>Nome:{{ $user->user_name }}</p>
        <p>Email:{{ $user->email }}</p>
        <p>Aniversário:</p>
    </div>
</body>

@stop